DROP DATABASE postgres;
ALTER DATABASE template0 IS_TEMPLATE FALSE;
DROP DATABASE template0;
ALTER DATABASE template1 IS_TEMPLATE FALSE;
DROP DATABASE template1;

\c mithril;
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(50) NOT NULL,
    intra_id INT UNIQUE,
    school_year VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true
);